/* eslint object-property-newline:0 */

// Function to get Country ID by passing Country Code
export function getCountryId(countryCode) {
  const countryID = {'AG': '01', 'BS': '02', 'BB': '03', 'BZ': '04', 'CA': '05', 'CR': '06',
    'CU': '07', 'DM': '08', 'DO': '09', 'SV': '10', 'GD': '11', 'GT': '12', 'HT': '13', 'HN': '14', 'JM': '15',
    'MX': '16', 'NI': '17', 'PA': '18', 'KN': '19', 'LC': '20', 'VC': '21', 'TT': '22', 'US': '23', 'GL': '24',
    'AR': '25', 'BO': '26', 'BR': '27', 'CL': '28', 'CO': '29', 'EC': '30', 'FK': '31', 'GF': '32', 'GY': '33',
    'PY': '34', 'PE': '35', 'SR': '36', 'UY': '37', 'VE': '38', 'DZ': '39', 'AO': '40', 'BJ': '41', 'BW': '42',
    'BF': '43', 'BI': '44', 'CM': '45', 'CV': '46', 'CP': '47', 'TD': '48', 'KM': '49', 'CI': '50', 'CD': '51',
    'DJ': '52', 'EG': '53', 'GQ': '54', 'ER': '55', 'ET': '56', 'GA': '57', 'GH': '58', 'GN': '59', 'GW': '60',
    'KE': '61', 'LS': '62', 'LI': '63', 'LR': '64', 'MS': '65', 'MW': '66', 'ML': '67', 'MR': '68', 'MA': '69',
    'MZ': '70', 'NA': '71', 'NE': '72', 'NG': '73', 'RW': '74', 'ST': '75', 'SN': '76', 'SC': '77', 'SL': '78',
    'SO': '79', 'ZA': '80', 'SD': '81', 'SZ': '82', 'TZ': '83', 'TG': '84', 'TN': '85', 'UG': '86', 'WA': '87',
    'ZM': '88', 'ZW': '89', 'GM': '90', 'CG': '91', 'MI': '92', 'AF': '93', 'AM': '94', 'AZ': '95', 'BD': '96',
    'BT': '97', 'BN': '98', 'MM': '99', 'KH': '100', 'CN': '101', 'TP': '102', 'GE': '103', 'IN': '104', 'ID': '105',
    'IA': '106', 'JP': '107', 'KZ': '108', 'KP': '109', 'KR': '110', 'KG': '111', 'LA': '112', 'MY': '113',
    'MN': '114', 'NP': '115', 'PK': '116', 'PH': '117', 'RU': '118', 'SG': '119', 'LK': '120', 'TJ': '121',
    'TH': '122', 'TM': '123', 'UZ': '124', 'VN': '125', 'TW': '126', 'HK': '127', 'MO': '128', 'AL': '129',
    'AD': '130', 'AT': '131', 'BY': '132', 'BE': '133', 'BH': '134', 'BG': '135', 'HY': '136', 'CZ': '137',
    'DK': '138', 'EE': '139', 'FI': '140', 'FR': '141', 'DE': '142', 'GR': '143', 'HU': '144', 'IS': '145',
    'IR': '146', 'IT': '147', 'LV': '148', 'LN': '149', 'LT': '150', 'LU': '151', 'MK': '152', 'MT': '153',
    'MV': '154', 'MC': '155', 'MG': '156', 'NL': '157', 'NO': '158', 'PL': '159', 'PT': '160', 'RO': '161',
    'SM': '162', 'CS': '163', 'SK': '164', 'SI': '165', 'ES': '166', 'SE': '167', 'CH': '168', 'UA': '169',
    'UK': '170', 'VA': '171', 'CY': '172', 'TK': '173', 'AU': '175', 'FJ': '176', 'KI': '177', 'MH': '178',
    'FM': '179', 'NR': '180', 'NZ': '181', 'PW': '182', 'PG': '183', 'WS': '184', 'SB': '185', 'TO': '186',
    'TV': '187', 'VU': '188', 'NC': '188', 'BA': '190', 'IZ': '191', 'IE': '192', 'JO': '193', 'KU': '194',
    'LB': '195', 'OM': '196', 'QA': '197', 'SA': '198', 'SY': '199', 'AE': '200', 'YM': '201', 'PR': '202',
    'KY': '203', 'SS': '204', 'KO': '205'};

  return countryID[countryCode];
}

export const getCountryCode = {
  'Antigua and Barbuda': 'AG',
  'Bahamas': 'BS',
  'Barbados': 'BB',
  'Belize': 'BZ',
  'Canada': 'CA',
  'Costa Rica': 'CR',
  'Cuba': 'CU',
  'Dominica': 'DM',
  'DominicanRep.': 'DO',
  'El Salvador': 'SV',
  'Grenada': 'GD',
  'Guatemala': 'GT',
  'Haiti': 'HT',
  'Honduras': 'HN',
  'Jamaica': 'JM',
  'Mexico': 'MX',
  'Nicaragua': 'NI',
  'Panama': 'PA',
  'St. Kitts &Nevis': 'KN',
  'St. Lucia': 'LC',
  'St. Vincent & the Grenadines': 'VC',
  'Trinidad & Tobago': 'TT',
  'United States': 'US',
  'Greenland': 'GL',
  'Argentina': 'AR',
  'Bolivia': 'BO',
  'Brazil': 'BR',
  'Chile': 'CL',
  'Colombia': 'CO',
  'Ecuador': 'EC',
  'Falkland Islands': 'FK',
  'French Guiana': 'GF',
  'Guyana': 'GY',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Suriname': 'SR',
  'Uruguay': 'UY',
  'Venezuela': 'VE',
  'Algeria': 'DZ',
  'Angola': 'AO',
  'Benin': 'BJ',
  'Botswna': 'BW',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cameroon': 'CM',
  'Cape Verde': 'CV',
  'Central African Republic': 'CP',
  'Chad': 'TD',
  'Comoros': 'KM',
  'Cote dIvoire': 'CI',
  'Democratic Republic of the Congo': 'CD',
  'Djibouti': 'DJ',
  'Egypt': 'EG',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Ethiopia': 'ET',
  'Gabon': 'GA',
  'Ghana': 'GH',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Kenya': 'KE',
  'Lesotho': 'LS',
  'Liberia': 'LI',
  'Liya': 'LR',
  'Madagascar': 'MS',
  'Malawi': 'MW',
  'Mali': 'ML',
  'Mauritania': 'MR',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Namibia': 'NA',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Rwana': 'RW',
  'Sao Tome and Principe': 'ST',
  'Senegal': 'SN',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'Sudan': 'SD',
  'Swaziland': 'SZ',
  'Tanzania': 'TZ',
  'Togo': 'TG',
  'Tunisia': 'TN',
  'Uganda': 'UG',
  'Western Sahara': 'WA',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Gambia': 'GM',
  'Congo': 'CG',
  'Mauritius': 'MI',
  'Afghanistan': 'AF',
  'Armenia': 'AM',
  'Azerbaijan': 'AZ',
  'Bangladesh': 'BD',
  'Bhutan': 'BT',
  'Brunei': 'BN',
  'Burma (Myanmar)': 'MM',
  'Cambodia': 'KH',
  'China': 'CN',
  'East Timor': 'TP',
  'Georgia': 'GE',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IA',
  'Japan': 'JP',
  'Kazakhstan': 'KZ',
  'Korea (north)': 'KP',
  'Korea (south)': 'KR',
  'Kyrgyzstan': 'KG',
  'Laos': 'LA',
  'Malaysia': 'MY',
  'Mongolia': 'MN',
  'Nepal': 'NP',
  'Pakistan': 'PK',
  'Philippines': 'PH',
  'Russia': 'RU',
  'Singapore': 'G',
  'Sri Lanka': 'LK',
  'Tajikistan': 'TJ',
  'Thailand': 'TH',
  'Turkmenistan': 'TM',
  'Uzbekistan': 'UZ',
  'Vietnam': 'VN',
  'Taiwan': 'TW',
  'Hong Kong': 'HK',
  'Macau': 'MO',
  'Albania': 'AL',
  'Andorra': 'AD',
  'Austria': 'AT',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Bosnia and Herzegovina': 'BH',
  'Bulgaria': 'BG',
  'Croatia': 'HY',
  'Czech Republic': 'CZ',
  'Denmark': 'DK',
  'Estonia': 'EE',
  'Finland': 'FI',
  'France': 'FR',
  'Germany': 'DE',
  'Greece': 'GR',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'Ireland': 'IR',
  'Itly': 'IT',
  'Latvia': 'LV',
  'Liechtenstein': 'LN',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macedonia': 'MK',
  'Malta': 'MT',
  'Moldova': 'MV',
  'Monaco': 'MC',
  'Montenegro': 'G',
  'Netherlands': 'NL',
  'Norway': 'NO',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Romania': 'RO',
  'San Marino': 'SM',
  'Serbia': 'CS',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Spain': 'ES',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Ukraine': 'UA',
  'United Kingdom': 'UK',
  'VaticanCity ': 'VA',
  'Cyprus': 'CY',
  'Turkey': 'TK',
  'Australia': 'AU',
  'Fiji': 'FJ',
  'Kiribati': 'KI',
  'Marshall Islands': 'MH',
  'Micronesia': 'FM',
  'Nauru': 'NR',
  'New Zealand': 'NZ',
  'Palau': 'PW',
  'Papua New Guinea': 'PG',
  'Samoa': 'WS',
  'Solomon Islands': 'SB',
  'Tonga': 'TO',
  'Tuvalu': 'TV',
  'Vanuatu': 'VU',
  'New Caledonia': 'NC',
  'Bahrain': 'BA',
  'Iraq': 'IZ',
  'Israel': 'IE',
  'Jordan': 'JO',
  'Kuwait': 'KU',
  'Lebanon': 'LB',
  'Oman': 'OM',
  'Qatar': 'QA',
  'Saudi Arabia': 'SA',
  'Syria': 'SY',
  'UnitedArabEmirates': 'AE',
  'Yemen': 'YM',
  'Puerto Rico': 'PR',
  'Cayman Islands': 'KY',
  'South Sudan': 'SS',
  'Kosovo': 'KO'
};

export const getCountryName = {
  'AD': 'Andorra',
  'AE': 'United Arab Emirates',
  'AF': 'Afghanistan',
  'AG': 'Antigua and Barbuda',
  'AI': 'Anguilla',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AN': 'Netherland Antilles',
  'AO': 'Angola',
  'AQ': 'Antarctica',
  'AR': 'Argentina',
  'AS': 'American Samoa',
  'AT': 'Austria',
  'AU': 'Australia',
  'AW': 'Aruba',
  'AZ': 'Azerbaidjan',
  'BA': 'Bosnia-Herzegovina',
  'BB': 'Barbados',
  'BD': 'Banglades',
  'BE': 'Belgium',
  'BF': 'Burkina Faso',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BI': 'Burundi',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BN': 'Brunei Darussalam',
  'BO': 'Bolivia',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BT': 'Buthan',
  'BV': 'Bouvet Island',
  'BW': 'Botswana',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'CA': 'Canada',
  'CC': 'Cocos (Keeling) Isl.',
  'CF': 'Central African Rep.',
  'CG': 'Congo',
  'CH': 'Switzerland',
  'CI': 'Ivory Coast',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CS': 'Czechoslovakia',
  'CU': 'Cuba',
  'CV': 'Cape Verde',
  'CX': 'Christmas Island',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DK': 'Denmark',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'EH': 'Western Sahara',
  'ES': 'Spain',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FK': 'Falkland Isl.(Malvinas)',
  'FM': 'Micronesia',
  'FO': 'Faroe Islands',
  'FR': 'France',
  'FX': 'France (European Ter.)',
  'GA': 'Gabon',
  'GB': 'Great Britain (UK)',
  'GD': 'Grenada',
  'GE': 'Georgia',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Greenland',
  'GP': 'Guadeloupe (Fr.)',
  'GQ': 'Equatorial Guinea',
  'GF': 'Guyana (Fr.)',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GR': 'Greece',
  'GT': 'Guatemala',
  'GU': 'Guam (US)',
  'GW': 'Guinea Bissau',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HM': 'Heard &amp; McDonald Isl.',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IN': 'India',
  'IO': 'British Indian O. Ter.',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KG': 'Kirgistan',
  'KH': 'Cambodia',
  'KI': 'Kiribati',
  'KM': 'Comoros',
  'KN': 'St.Kitts Nevis Anguilla',
  'KP': 'Korea (North)',
  'KR': 'Korea (South)',
  'KW': 'Kuwait',
  'KY': 'Cayman Islands',
  'KZ': 'Kazachstan',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LC': 'Saint Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'LY': 'Libya',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldavia',
  'MG': 'Madagascar',
  'MH': 'Marshall Islands',
  'ML': 'Mali',
  'MM': 'Myanmar',
  'MN': 'Mongolia',
  'MO': 'Macau',
  'MP': 'Northern Mariana Isl.',
  'MQ': 'Martinique (Fr.)',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MW': 'Malawi',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NC': 'New Caledonia (Fr.)',
  'NE': 'Niger',
  'NF': 'Norfolk Island',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NT': 'Neutral Zone',
  'NU': 'Niue',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'Polynesia (Fr.)',
  'PG': 'Papua New',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Poland',
  'PM': 'St. Pierre &amp; Miquelon',
  'PN': 'Pitcairn',
  'PT': 'Portugal',
  'PR': 'Puerto Rico (US)',
  'PW': 'Palau',
  'PY': 'Paraguay',
  'QA': 'Qatar',
  'RE': 'Reunion (Fr.)',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SA': 'Saudi Arabia',
  'SB': 'Solomon Islands',
  'SC': 'Seychelles',
  'SD': 'Sudan',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'SH': 'St. Helena',
  'SI': 'Slovenia',
  'SJ': 'Svalbard &amp; Jan Mayen',
  'SK': 'Slovak Republic',
  'SL': 'Sierra Leone',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Suriname',
  'ST': 'St. Tome and Princip',
  'SU': 'Soviet Union',
  'SV': 'El Salvador',
  'SY': 'Syria',
  'SZ': 'Swaziland',
  'TC': 'Turks &amp; Caicos Islands',
  'TD': 'Chad',
  'TF': 'French Southern Terr.',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tadjikistan',
  'TK': 'Tokelau',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TP': 'East Timor',
  'TR': 'Turkey',
  'TT': 'Trinidad &amp; Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'UK': 'United Kingdom',
  'UM': 'US Minor outlying Isl.',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VA': 'Vatican City State',
  'VC': 'St.Vincent &amp; Grenadines',
  'VE': 'Venezuela',
  'VG': 'Virgin Islands (British)',
  'VI': 'Virgin Islands (US)',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis &amp; Futuna Islands',
  'WS': 'Samoa',
  'YE': 'Yemen',
  'YU': 'Yugoslavia',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZR': 'Zaire',
  'ZW': 'Zimbabwe'
};
