import {
  generateDataArray,
  generateChartDataSource
} from 'components/HorizontalBarChart';

describe('HorizontalBarChart Component: ', function() {
  it('generateDataArray should return data array.', function() {
    const columnIndexArray = [3, 4],
      rowsArray = [['IN', '1463.5', '557.45', 'India', 33, 334692], ['CN', '1681.14', '479.81', 'China', 6, 15520],
      ['UA', '1184.78', '395.81', 'Ukraine', 5, 13940], ['HK', 'N/A', 'N/A', 'Hong Kong', 4, 15976],
      ['CA', '566.23', '428.9', 'Canada', 3, 28132], ['US', '547.14', '484.9', 'United States', 3, 781274],
      ['BR', '713.87', '796.72', 'Brazil', 1, 3738], ['FR', '1012.96', '407.27', 'France', 1, 43],
      ['SE', '1105.87', '319.45', 'Sweden', 1, 0]],
      dataArray = [{'label': 'India', 'value': 33, 'toolText': 'India, 33'},
      {'label': 'China', 'value': 6, 'toolText': 'China, 6'},
      {'label': 'Ukraine', 'value': 5, 'toolText': 'Ukraine, 5'},
      {'label': 'Hong Kong', 'value': 4, 'toolText': 'Hong Kong, 4'},
      {'label': 'Canada', 'value': 3, 'toolText': 'Canada, 3'},
      {'label': 'United States', 'value': 3, 'toolText': 'United States, 3'},
      {'label': 'Brazil', 'value': 1, 'toolText': 'Brazil, 1'},
      {'label': 'France', 'value': 1, 'toolText': 'France, 1'},
      {'label': 'Sweden', 'value': 1, 'toolText': 'Sweden, 1'}];
    expect(generateDataArray(columnIndexArray, rowsArray)).to.deep.equal(dataArray);
  });

  it('generateChartDataSource should return chart datasource object.', function() {
    const rawData = {'taf_source_countries': {'total': -1, 'next': -1,
    'columns': [{'name': 'source.country', 'displayName': 'source.country', 'columnType': 'DIMENSION',
    'dataType': 'TEXT', 'sortable': true}, {'name': 'pos_x', 'displayName': 'pos_x', 'columnType': 'DIMENSION',
    'dataType': 'TEXT', 'sortable': true}, {'name': 'pos_y', 'displayName': 'pos_y', 'columnType': 'DIMENSION',
    'dataType': 'TEXT', 'sortable': true}, {'name': 'country_name', 'displayName': 'country_name',
    'columnType': 'DIMENSION', 'dataType': 'TEXT', 'sortable': true}, {'name': 'connections',
    'displayName': 'connections', 'columnType': 'MEASURE', 'dataType': 'NUMBER', 'sortable': true},
    {'name': 'bandwidth', 'displayName': 'bandwidth', 'columnType': 'FORMULA', 'dataType': 'NUMBER',
    'sortable': true}], 'rows': [['IN', '1463.5', '557.45', 'India', 39, 393872], ['CN', '1681.14', '479.81',
    'China', 5, 15520], ['UA', '1184.78', '395.81', 'Ukraine', 5, 13940], ['HK', 'N/A', 'N/A', 'Hong Kong', 4, 15976],
    ['US', '547.14', '484.9', 'United States', 3, 781274], ['CA', '566.23', '428.9', 'Canada', 2, 16613],
    ['BR', '713.87', '796.72', 'Brazil', 1, 3738], ['FR', '1012.96', '407.27', 'France', 1, 43],
    ['SE', '1105.87', '319.45', 'Sweden', 1, 0]]}},
      props = {'type': 'HorizontalBarChart', 'parent': 'Compound',
      'meta': {'showHeader': false, 'title': 'Top 5 Connections'},
      'attributes': {'style': {'width': '48%', 'marginRight': '20px'},
      'id': 'IncomingTopCountries', 'chartBorder': {'border': '3px solid #BBBABA', 'float': 'left',
      'width': '48%', 'margin': '1%'}, 'chartCaption': {'width': '100%', 'color': '#555555',
      'fontFamily': 'Verdana,sans', 'fontSize': '14px', 'fontWeight': 'bold', 'textAlign': 'center',
      'paddingTop': '10px'}, 'chartWidth': '100%', 'chartHeight': '200'}, 'chartOptions': {},
      'chartData': {'multipleReportIds': false, 'displayTopFive': true, 'showTrendLines': false,
      'fieldMapping': [{'reportId': 'taf_source_countries', 'columns': ['country_name', 'connections']}]},
      'children': [], 'data': {'taf_source_countries': {'total': -1, 'next': -1,
      'columns': [{'name': 'source.country', 'displayName': 'source.country', 'columnType': 'DIMENSION',
      'dataType': 'TEXT', 'sortable': true}, {'name': 'pos_x', 'displayName': 'pos_x', 'columnType': 'DIMENSION',
      'dataType': 'TEXT', 'sortable': true}, {'name': 'pos_y', 'displayName': 'pos_y', 'columnType': 'DIMENSION',
      'dataType': 'TEXT', 'sortable': true}, {'name': 'country_name', 'displayName': 'country_name',
      'columnType': 'DIMENSION', 'dataType': 'TEXT', 'sortable': true},
      {'name': 'connections', 'displayName': 'connections', 'columnType': 'MEASURE', 'dataType': 'NUMBER',
      'sortable': true}, {'name': 'bandwidth', 'displayName': 'bandwidth', 'columnType': 'FORMULA',
      'dataType': 'NUMBER', 'sortable': true}], 'rows': [['IN', '1463.5', '557.45', 'India', 39, 393872],
      ['CN', '1681.14', '479.81', 'China',5, 15520], ['UA', '1184.78', '395.81', 'Ukraine', 5, 13940],
      ['HK', 'N/A', 'N/A', 'Hong Kong', 4, 15976], ['US', '547.14', '484.9', 'United States', 3, 781274],
      ['CA', '566.23', '428.9', 'Canada', 2, 16613], ['BR', '713.87', '796.72', 'Brazil', 1, 3738],
      ['FR', '1012.96', '407.27', 'France', 1, 43], ['SE', '1105.87', '319.45', 'Sweden', 1, 0]]},
      'taf_source_bad_reputation_countries': {'total': -1, 'next': -1, 'columns': [{'name': 'source.country',
      'displayName': 'source.country', 'columnType': 'DIMENSION', 'dataType': 'TEXT', 'sortable': true},
      {'name': 'pos_x', 'displayName': 'pos_x', 'columnType': 'DIMENSION', 'dataType': 'TEXT', 'sortable': true},
      {'name': 'pos_y', 'displayName': 'pos_y', 'columnType': 'DIMENSION', 'dataType': 'TEXT', 'sortable': true},
      {'name': 'country_name', 'displayName': 'country_name', 'columnType': 'DIMENSION', 'dataType': 'TEXT',
      'sortable': true}, {'name': 'connections', 'displayName': 'connections', 'columnType': 'MEASURE',
      'dataType': 'NUMBER', 'sortable': true}, {'name': 'bandwidth', 'displayName': 'bandwidth',
      'columnType': 'FORMULA', 'dataType': 'NUMBER', 'sortable': true}], 'rows': [['CN', '1681.14',
      '479.81', 'China', 2, 7988], ['SE', '1105.87', '319.45', 'Sweden', 1, 0]]}}, 'duration': '1h'},
      dataSourceObject = {'chart': {'bgColor': '#ffffff', 'showborder': '0', 'borderThickness': '0',
      'showCanvasBorder': '0', 'usePlotGradientColor': '0', 'plotBorderAlpha': '10', 'placeValuesInside': '1',
      'valueFontColor': '#111111', 'showAxisLines': '0', 'axisLineAlpha': '25', 'numDivLines': '0',
      'divLineAlpha': '10', 'alignCaptionWithCanvas': '0', 'showAlternateVGridColor': '0', 'captionFontSize': '14',
      'subcaptionFontSize': '12', 'subcaptionFontBold': '0', 'toolTipColor': '#ffffff', 'toolTipBorderThickness': '0',
      'toolTipBgColor': '#000000', 'toolTipBgAlpha': '80', 'toolTipBorderRadius': '2', 'toolTipPadding': '5',
      'showYAxisValues': '0', 'showValues': '1', 'paletteColors': '#ACF50F,#D93609,#FCFC0D, #05E9F5,#0505F5',
      'xAxisNameFontSize': '14', 'yAxisNameFontSize': '14', 'labelFontSize': '13'}, 'data': [{'label': 'India',
      'value': 39, 'toolText': 'India, 39'}, {'label': 'China', 'value': 5, 'toolText': 'China, 5'},
      {'label': 'Ukraine', 'value': 5, 'toolText': 'Ukraine, 5'}, {'label': 'Hong Kong', 'value': 4,
      'toolText': 'Hong Kong, 4'}, {'label': 'United States', 'value': 3, 'toolText': 'United States, 3'}]};
    expect(generateChartDataSource(rawData, props)).to.deep.equal(dataSourceObject);
  });
});
