export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';
export const ERROR_API_DATA = 'ERROR_API_DATA';
export const UPDATE_API_DATA = 'UPDATE_API_DATA';

export const TIME_INTERVAL_UPDATE = 'TIME_INTERVAL_UPDATE';

export const USER_DETAILS_LOADING = 'USER_DETAILS_LOADING';
export const USER_DETAILS_LOADED = 'USER_DETAILS_LOADED';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export const REQUEST_LAYOUT_DATA = 'REQUEST_LAYOUT_DATA';
export const RECEIVE_LAYOUT_DATA = 'RECEIVE_LAYOUT_DATA';
export const ERROR_LAYOUT_DATA = 'ERROR_LAYOUT_DATA';

export const LOW_SCORE_RANGE = [1, 34];
export const MEDIUM_SCORE_RANGE = [35, 64];
export const HIGH_SCORE_RANGE = [65, 100];
