export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';
export const ERROR_API_DATA = 'ERROR_API_DATA';
export const UPDATE_API_DATA = 'UPDATE_API_DATA';

export const TIME_INTERVAL_UPDATE = 'TIME_INTERVAL_UPDATE';
